version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.3
    container_name: es6
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - http.cors.allow-origin=/.*/
      - http.cors.enabled=true 
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
